project:
    type: tufte
book:
  open-graph: true
  site-url: https://derecksprojects.com/
  repo-url: https://github.com/derecksprojects/derecksprojects.com/
  repo-actions: [issue]
  title: |
    Dereck's Projects\
    Software | Bioinformatics | Data Science
  subtitle: Yeet
  title-short: Software and data consulting # title-short is used in the pdf head
  output-file: derecksprojects.com # outputs: docs/TufteStyledBook.pdf
  author: Dereck Mezquita
  publisher: Dereck Mezquita
  date-format: YYYY-MMMM-DD
  license: "CC BY"
  chapters:
    - index.qmd
    - 02-Main/customizing.qmd
    - 02-Main/known_issues.qmd
    - part: about.qmd
      chapters:
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
bibliography: references.bib
